version: '3'
services:
  backend:
    build:
      context: ./test-project/api


    ports:
      - "5000:5000"

    networks:
      - my_network

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - my_network

  frontend:
    build:
      context: ./test-project/sys-stats
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my_network



networks:
  my_network:
